language: python

python:
  - 3.6

services:
  - docker

before_install:
  - make start-containers

script:
  - make tests

addons:
  ssh_known_hosts: 49.12.6.114

before_deploy:
  - openssl aes-256-cbc -K $encrypted_c7065a1712c1_key -iv $encrypted_c7065a1712c1_iv -in infrastructure/playbooks/travis_secrets.tar.enc -out infrastructure/playbooks/travis_secrets.tar -d
  - tar xvf infrastructure/playbooks/travis_secrets.tar
  - eval "$(ssh-agent -s)"
  - chmod 600 infrastructure/playbooks/deploy_rsa
  - ssh-add infrastructure/playbooks/deploy_rsa
  - pip install ansible

deploy:
  skip_cleanup: true
  provider: script
  script: ansible-playbook infrastructure/playbooks/deploy.yml -i infrastructure/playbooks/hosts --vault-password-file infrastructure/playbooks/vault_password.txt
  on:
    branch: master
