language: python

python:
  - 3.6

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_c7065a1712c1_key -iv $encrypted_c7065a1712c1_iv -in vault_password.txt.enc -out infrastructure/playbooks/vault_password.txt -d
  - make start-containers
  - until curl --silent -XGET --fail http://localhost:5200/robots.txt; do printf '.'; sleep 1; done
  - make migrations

script:
  - make test
