apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepy
  labels:
    app: pepy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepy
  template:
    metadata:
      labels:
        app: pepy
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-account-credentials
        - name: newrelic-config
          secret:
            secretName: newrelic-config
      containers:
        - name: pepy
          image: ghcr.io/psincraian/pepy
          env:
            - name: APPLICATION_ENV
              value: prod
            - name: PEPY_LOGGING_FILE
              value: app.log
            - name: PEPY_BIGQUERY_CREDENTIALS
              value: /var/secrets/google/bq_credentials.json
            - name: NEW_RELIC_CONFIG_FILE
              value: /var/secrets/newrelic/newrelic.ini
            - name: PEPY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pepy-secrets
                  key: admin-password
                  optional: false
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "25m"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: newrelic-config
              mountPath: /var/secrets/newrelic
      imagePullSecrets:
        - name: dockerconfigjson-github-com