---

- include_vars: pepy.yml

- name: Ensure cron variables are set
  cron:
    name: "{{ item.name }}"
    env: yes
    value: "{{ item.value }}"
    user: "{{ pepy_user }}"
  with_items:
    - "{{ pepy_env }}"
  no_log: true

- name: Ensure update downloads cron exists (root user deprecated)
  cron:
    name: "update daily downloads"
    minute: "0"
    hour: "17"
    job: "cd {{ project_directory }} && .venv/bin/python -m pepy import:downloads:day --password \"{{ admin_password_plain }}\""
    state: absent

- name: Ensure update downloads cron exists
  cron:
    name: "update daily downloads"
    minute: "0"
    hour: "17"
    job: "cd {{ project_directory }} && .venv/bin/python -m pepy import:downloads:day --password \"{{ admin_password_plain }}\" || dog event post --alert_type error --tags cli \"Update daily downloads cron failed\" \"Check the cli command or the logs for more info\""
    user: "{{ pepy_user }}"
