---

- name: Install Nginx
  apt: name=nginx update_cache=yes state=present

- name: Copy SSL fullchain.pem
  copy:
    src: fullchain.pem
    dest: /etc/letsencrypt/live/pepy.tech/

- name: Copy SSL fullchain.pem
  copy:
    src: privkey.pem
    dest: /etc/letsencrypt/live/pepy.tech/

- name: Create the Nginx configuration file
  template: src=pepy.conf
            dest=/etc/nginx/sites-available/{{ project_name }}.conf
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ project_name }}.conf
    dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
    state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Reload nginx
  service: name=nginx state=restarted