version: '3'

services:
  pepy:
    image: ghcr.io/psincraian/pepy:${PEPY_VERSION}
    environment:
      - APPLICATION_ENV=dev
      - FLASK_DEBUG=1
      - SHELL=/bin/bash
    ports:
      - 5200:8080
    volumes:
      - ./:/code
    links:
      - mongodb:mongodb
    command: "gunicorn -c /code/infrastructure/dockerfiles/pepy/gunicorn.conf.py pepy.infrastructure.web.__init__:app"

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/datadb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pepy
      - MONGO_INITDB_ROOT_PASSWORD=pepy

  pepy-test:
    image: ghcr.io/psincraian/pepy-test:${PEPY_VERSION}
    environment:
      - APPLICATION_ENV=tests
      - FLASK_DEBUG=1
      - SHELL=/bin/bash
    volumes:
      - ./:/code
    links:
      - mongodb:mongodb
    command: sleep infinity

volumes:
  mongodb_data: {}
