
FROM centos:8

# Updating the default repo to vault.centos.org
# Context: https://forketyfork.medium.com/centos-8-no-urls-in-mirrorlist-error-3f87c3466faa
RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* \
    && sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*

# Run a system update so the system doesn't overwrite the fake systemctl later
RUN yum -y update
# Install sudo which is required by targz installation script
RUN yum -y install sudo

# Adding fake systemctl and python
RUN curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py -o /usr/bin/systemctl \
 && yum install python3 -y
