name: CI and CD

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Authenticate docker
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u psincraian --password-stdin
    - name: Start environment
      run: make start-containers
    - name: Run tests
      run: make params=-T tests
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v1
    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ./infrastructure/playbooks/deploy.yml
        directory: ./
        key: ${{secrets.SSH_KEY}}
        vault_password: ${{secrets.VAULT_PASSWORD}}
        options: |
          --inventory infrastructure/playbooks/hosts
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
