name: CI and CD

on:
  push:
    branches:
    - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Start environment
      run: make start-containers
    - name: Run tests
      run: make params=-T tests
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v1
    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.2.0
      with:
        playbook: ./infrastructure/playbooks/deploy.yml
        directory: ./
        key: ${{secrets.SSH_KEY}}
        inventory: |
          [webservers]
          root@49.12.6.114 ansible_python_interpreter=/usr/bin/python3
        vault_password: ${{secrets.VAULT_PASSWORD}}
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
